language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t awnaarali73/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true awnaarali73/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-2-833804465701"
  bucket_path: "docker-react" # Should be equal to the app name
  on:
    branch: master # link to github
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
