version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:   # Correct volume mounting is very important if you want make local changes that you want to reflect in the running container. You could create a local genesis file and then export it to all the running containers.
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"] # in a similar fashion you can configure your blockchain nodes
